name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: pnpm i
      - run: pnpm clean
      - run: pnpm build
      - run: pnpm dlx @plasmohq/mystic-box test-zip 0.0.8
      - uses: PlasmoHQ/soft-secret@v1
        with:
          secret: ${{ secrets.TEST_KEY }}
          target: "key.json"
      - run: pnpm test
